# Generated by Django 5.1.4 on 2025-02-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('package_name', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=60)),
                ('phno', models.CharField(max_length=12)),
                ('status', models.CharField(default='Requested', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('package_id', models.AutoField(primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=100)),
                ('package_destinations', models.TextField(max_length=500)),
                ('package_days', models.IntegerField()),
                ('package_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=60)),
                ('phno', models.CharField(max_length=12, unique=True)),
                ('pswd', models.CharField(max_length=16)),
            ],
        ),
    ]
