# Generated by Django 5.1.4 on 2025-02-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='package_name',
            field=models.CharField(max_length=100),
        ),
    ]
