# Generated by Django 5.1.4 on 2025-02-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_alter_booking_package_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booked_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='available_month',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
