# Generated by Django 5.1.4 on 2025-02-11 14:44

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_booking_booked_date_package_available_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='available_month',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March')], max_length=22),
        ),
    ]
