# Generated by Django 5.1.4 on 2025-02-11 15:30

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_alter_package_available_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='available_month',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December'), ('Every Month', 'Every Month')], default='January', max_length=97),
        ),
    ]
