# Generated by Django 5.1.4 on 2025-02-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_alter_package_available_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='available_month',
        ),
        migrations.AddField(
            model_name='package',
            name='allowed_months',
            field=models.JSONField(default=list),
        ),
    ]
