# Generated by Django 5.1.4 on 2025-02-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_alter_package_available_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booked_date',
            new_name='date',
        ),
        migrations.AddField(
            model_name='booking',
            name='No_persons',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='amt',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
