# Generated by Django 5.1.4 on 2025-02-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0011_rename_booked_date_booking_date_booking_no_persons_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='No_persons',
            new_name='persons',
        ),
        migrations.RemoveField(
            model_name='package',
            name='available_month',
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
