# Generated by Django 5.1.4 on 2025-02-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0012_rename_no_persons_booking_persons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.CharField(max_length=12),
        ),
    ]
