# Generated by Django 5.1.4 on 2025-02-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0013_alter_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='amt',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='persons',
            field=models.IntegerField(),
        ),
    ]
