# Generated by Django 5.1.4 on 2025-02-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0015_alter_booking_payment_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
